const N_LETTER_SEQUENCES_FOR_MUTANT = 4;
const MINIMAL_MATCHES_FOR_MUTANT = 2;
const VALID_LETTERS = ['A', 'T', 'C', 'G'];

module.exports = {
    N_LETTER_SEQUENCES_FOR_MUTANT,
    MINIMAL_MATCHES_FOR_MUTANT,
    VALID_LETTERS
}